import turtle
turtle.up()
turtle.shape('turtle')
turtle.goto(0,0)
turtle.color('black')
turtle.down()
turtle.begin_fill()
turtle.forward(100)
turtle.right(120)
turtle.forward(100)
turtle.right(60)
turtle.forward(100)
turtle.right(120)
turtle.forward(100)
turtle.end_fill()

turtle.up()
turtle.shape('turtle')
turtle.goto(100,0)
turtle.color('blue')
turtle.down()
turtle.begin_fill()
turtle.left(60)
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.end_fill()

turtle.up()
turtle.shape('turtle')
turtle.color('red')
turtle.down()
turtle.begin_fill()
turtle.left(180)
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.end_fill()

turtle.hideturtle()
turtle.done()